@echo off

::
:: THIS RUN SCRIPT IS PROVIDED BY AMELIE HEINRICH -- IF YOU HAVE ANY QUESTIONS, REFER TO THE FOLLOWING EMAIL ADDRESS: aheinrich@gaming.tech
:: CE SCRIPT DE RUN A ETE ECRIT PAR AMELIE HEINRICH -- SI VOUS AVEZ DES QUESTIONS, ENVOYEZ LES MOI A CETTE ADRESSE EMAIL: aheinrich@gaming.tech
::

call run_tree\IA.exe
